### ISSUE TITLE
Grayscale and Stylish_portfolio Themes was aborted

### ISSUE THREAD

**Issue by romenigld** [MrPowers/frontend-generators#11]
Hey Guys, firts I want to thank's for this incredible gem, this help a lot!
The stylish_portfolio and creative Themes works perfectly in my app. 
But when I try to use the cleand Blog or Grayscale Themes. Wasn't possible to run the
 `bundle exec rake add_assets:grayscale`.
It was aborted. My logs:

```
bundle exec rake add_assets:grayscale
rake aborted!
Don't know how to build task 'add_assets:grayscale'

(See full trace by running task with --trace)
```

```
bundle exec rake add_assets:clean_blog
rake aborted!
Don't know how to build task 'add_assets:clean_blog'

(See full trace by running task with --trace)
```

**Comment by MrPowers** [comment]
@romenigld - Thanks for reporting this :+1: 

I'll look into these bugs and get back to you :smile:

**Comment by MrPowers** [comment]
I made some bug fixed and pushed the latest gem to RubyGems.  Add this to your Gemfile and see if you can get the rake tasks to work: `gem 'frontend-generators', '0.1.1'`

There are still bugs in the clean blog theme and I don't know when I'll have time to fix them.  If you're feeling ambitious, please send a pull request!  Thanks!

**Comment by romenigld** [comment]
Thank's Mr. Powers!

**Comment by rhuberdeau** [comment]
I haven't been able to replicate this bug. Closing.

**Comment by MrPowers** [comment]
Thanks @rhuberdeau!!!

@romenigld - Let us know if you were ever able to get your issue resolved!

**Comment by romenigld** [comment]
Hello @MrPowers, this is was a lot of time ago. 
I really like this gem, this helps you a lot for use this templates. But I don't remember anymore what happened when I try to use this. Was for a project that I worked. 
Now I'm doing some things. 
But I will try to test this gem when I have finished this things. 
So I will tell you something about my experience. 
Regard's!!!
