### ISSUE TITLE
Creative Theme

### ISSUE THREAD

**Issue by stilomatic** [MrPowers/frontend-generators#12]
Sorry i am pretty new to rail.

I've followed the instructions in the read.md but the creatives theme is installed but not displayed.

If you can give me some hints. Thanks

that's my system:

Rails version   4.2.5
Ruby version    2.2.3-p173 (x86_64-darwin15)
RubyGems version    2.4.5.1
Rack version    1.6.4
JavaScript Runtime  JavaScriptCore
Middleware  
Rack::Sendfile
ActionDispatch::Static
Rack::Lock
# ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007fa48a415088

Rack::Runtime
Rack::MethodOverride
ActionDispatch::RequestId
RequestStore::Middleware
Rails::Rack::Logger
ActionDispatch::ShowExceptions
WebConsole::Middleware
ActionDispatch::DebugExceptions
ActionDispatch::RemoteIp
ActionDispatch::Reloader
ActionDispatch::Callbacks
ActiveRecord::Migration::CheckPending
ActiveRecord::ConnectionAdapters::ConnectionManagement
ActiveRecord::QueryCache
ActionDispatch::Cookies
ActionDispatch::Session::CookieStore
ActionDispatch::Flash
ActionDispatch::ParamsParser
Rack::Head
Rack::ConditionalGet
Rack::ETag

**Comment by MrPowers** [comment]
Thanks for the comment :smile: 

Did you go to localhost:3000/creatives/index?  What was the error message you got?  Thanks!

**Comment by stilomatic** [comment]
No error: there the Theme is up :)

**Comment by stilomatic** [comment]
i think the issue is in route.rb but i followed your explanation and i pasted the get 'creatives/index'
I am also running a CMS: Casein and there is already a generated code for it in the route.rb

**Comment by MrPowers** [comment]
It sounds like everything is working properly :)

Thanks!
