### ISSUE TITLE
SB-Admin-2 Rake was aborted

### ISSUE THREAD

**Issue by garycwallen** [MrPowers/frontend-generators#13]
bundle exec rake add_assets:sb-admin-2
rake aborted!
Don't know how to build task 'add_assets:sb-admin-2' (see --tasks)
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`<main>'
(See full trace by running task with --trace)

**Comment by MrPowers** [comment]
I don't think this theme has been added to the project yet.  If you're feeling ambitious, send a pull request and I'll merge it in 😄

**Comment by toxic2302** [comment]
Yeah...please add it to the project :D

**Comment by rhuberdeau** [comment]
This is a duplicate of issue #2

**Comment by MrPowers** [comment]
Thanks @rhuberdeau
