### ISSUE TITLE
Can I Use WrapBootstrap Premium Themes?

### ISSUE THREAD

**Issue by lanrewajub** [MrPowers/frontend-generators#14]
Awesome gem you have there, 

Pleas can I install WrapBootstrap Premium Themes using this gem?

Regards

**Comment by MrPowers** [comment]
Thanks for the message.

This gem doesn't include any WrapBootstrap Premium Themes.  You can follow the design patterns in this gem to add the WrapBootstrap Premium Themes to your site.  Good luck!
