### ISSUE TITLE
Styles are not importing correctly

### ISSUE THREAD

**Issue by rhuberdeau** [MrPowers/frontend-generators#20]
Using "*= require bootstrap" in application.css as described in the README does not allow the specific styles associated with each theme to over write the default bootstrap styles.

  To replicate, create a new rails app, install the frontend-generators gem, follow the install instructions, install the clean-blog theme. Load up a page and compare it to the live preview version. Notice some of the text styling is missing.

  To fix this, we need to move to import rather than require. For example, we just need to create main.scss in the same folder as application.scss and add @import "bootstrap";

**Comment by MrPowers** [comment]
Great catch @rhuberdeau 😄 

I'm looking forward for a fix to get merged in!
