### ISSUE TITLE
font-awesome not working in production

### ISSUE THREAD

**Issue by austinarchibald** [MrPowers/frontend-generators#24]
everything works fine on my localhost server. but when I deployed to production, all font-awesome icons appear as boxes. any suggestions? thank you

**Comment by austinarchibald** [comment]
okay, adding `@import "font-awesome";` to creative.css.scss fixed it. not sure why that's required in production but not in development

**Comment by MrPowers** [comment]
Thanks for following up on this one @austinarchibald.  Do you have any interest in becoming a maintainer of this project?  I'm not a Rails developer anymore (I switched to Spark/Scala/Python) and would like people like you to keep this project alive and healthy 😄
