### ISSUE TITLE
Port the Greyscale theme

### ISSUE THREAD

**Issue by MrPowers** [MrPowers/frontend-generators#6]
Link to theme: http://startbootstrap.com/template-overviews/grayscale/

**Comment by martinnabhan** [comment]
I'm looking into this now! It seems the Freelancer theme is very similar so I might take some hints from there.

**Comment by MrPowers** [comment]
Great, thanks!  A couple of your files were executables in the last pull request.  Can you make sure the files aren't executable this time :smile: 

Take some of the Bash quizzes on CodeQuizzes if you aren't sure about what executable files are.

Thanks again for the awesome help.

**Comment by martinnabhan** [comment]
Thanks for the tip about the quizzes, they helped a lot! I've added the new commits to the pull request so please take a look.

**Comment by MrPowers** [comment]
@MartinN13 - Thanks again for the help with this.  This was merged with master (a while ago), so I'm going to close this issue.
